all : p1 p2 p3 p4

p1 : p1.c
	gcc -o p1 p1.c -Wall -Wfatal-errors


p2 : p2.c
	gcc -o p2 p2.c -Wall -Wfatal-errors


p3 : p3.c
	gcc -o p3 p3.c -Wall -Wfatal-errors

p4 : p4.c
	gcc -o p4 p4.c -Wall -Wfatal-errors

clean : 
	rm -f p1 p2 p3 p4 p4.output

